set nocompatible              " be iMproved, required
filetype off                  " required

" *** Begining of the plugin list ***

call plug#begin('~/.vim/plugged')

" Git wrapper
Plug 'tpope/vim-fugitive'

" Fast file navigation
Plug 'wincent/command-t'

" Parser for an easy HTML format
Plug 'rstacruz/sparkup', {'rtp': 'vim/'}

" A low-contrast colorscheme
Plug 'junegunn/seoul256.vim'

" Autocompletion with deep learning
Plug 'zxqfl/tabnine-vim'

" *** Additional plugins. Uncomment if you need them. ***

" Rust syntax highlighting
" Plug 'wting/rust.vim'

" Coffeescript syntax highlighting
" Plug 'kchmck/vim-coffee-script'

" Arduino syntax highlighting
" Plug 'sudar/vim-arduino-syntax'

" html5 support
" Plug 'othree/html5.vim'

" Plug 'Shougo/neocomplete.vim'

" Plug 'vim-scripts/taglist.vim'

" Plug 'vim-scripts/srcexpl' 

call plug#end()

" *** End of the plugin list ***



" *** editor settings ***

" Enable line numbers
set number

" Enable mouse in all modes
set mouse=a

" set ai

" set si

" Enable syntax highlighting
syntax on

" Highlight searches
set hlsearch

" Highlight dynamically as pattern is typed
set incsearch

" Show the command as it's being typed
set showcmd

" Show the cursor position
set ruler

" Show the filename
set title

" Show the current mode
set showmode

set nobackup

" Use UTF-8 without BOM
set encoding=utf-8 nobomb

" Set the tab stop as wide as two spaces
set ts=2

set sw=2
set sts=2

" Allow backspace in insert mode
set backspace=indent,eol,start

" Allow cursor keys in insert mode
set esckeys

set completeopt-=preview

" Enhance command-line completion
set wildmenu


" *** colorscheme settings ***

" Set background brightness. Range: 233 (darkest) ~ 239 (brightest)
let g:seoul256_background = 237

" Display correct color in (most of) linux terminal emulators
let g:seoul256_srgb = 1 

" Use dark color scheme
colo seoul256 
