source ~/.zgen.zsh
if ! zgen saved; then
	echo "Creating a zgen save"

	zgen oh-my-zsh
	zgen oh-my-zsh plugins/cp
	zgen oh-my-zsh plugins/git
	zgen oh-my-zsh plugins/mosh
	zgen oh-my-zsh plugins/command-not-found
	zgen load zsh-users/zsh-completions src
	zgen load zsh-users/zsh-syntax-highlighting
	zgen oh-my-zsh themes/agnoster
	zgen save
fi

#export TERM=xterm-256color
export ZSH_THEME=agnoster
export DEFAULT_USER="$USER"

alias c="clear"
alias cl="clear;l"

# for ls
alias l='ls'
alias la='ls -a'
alias ll='ls -lh'

# for tmux
alias t='tmux'
alias ta='tmux attach'
alias tl='tmux ls'

alias vi='vim'

# for git
# for mac old version problem
#export PATH="$(find /usr/local/Cellar -type d -name bin):${PATH}"

